# -*- coding: utf-8 -*-
"""Cappuccina_week_4_webdev1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtupvSWfXgg5BbLufytJN9Me_jjak454

# Dashboards

### What is a dashboard?
A dashboard is an interface to visually display data analytics in an interactive and interprative way.

Some examples of dashboards are at this link: https://streamlit.io/gallery

What is Streamlit?
Streamlit is a Python library that streamlines the whole web development process. It is most commonly used for data science to create visually appealing and interactive interfaces. With Streamlit, you can create a whole website just using Python, without having to separate frontend and backend code.

This notebook lesson will introduce you to lines of code you can use in your Streamlit applications. Unfortunately, you cannot actually run the website and see your dashboard using Google Colab, so we will have to use our personal computers to actually create the websites!

To run your website:


1.   Create a new directory on your computer, e.g. `webDevFolder`
2.   Create a new Python file within that directory, e.g. `app.py`
3.   Write your Streamlit code within that Python file on an interface where you can write Python code
4.   In the Terminal, make sure you are in the new directory you created. If not, write `cd webDevFolder`
5.   Run the ap by typing `streamlit run app.py`



Let's go through some simple lines of code and syntax for streamlit!

Text/structure: st.title, st.header, st.write

Widgets: st.button, st.slider, st.selectbox

Charts: st.line_chart, st.bar_chart, st.pyplot

## Setting Up Your Computer



1.   Have somewhere to write Python code. Some options are Visual Studio Code, Cursor, etc. Download to your computer.
2.   Install Conda or Miniconda onto your computer (Google Conda installation and follow steps).
3.   Go to your computer's terminal.
4.   Create a new conda environment with *pandas*, *numpy*, and *matplotlib*. You can do this by typing the following into your terminal: `conda create --name myenv numpy pandas matplotlib` where you replace *myenv* with your chosen name for the environment. Let's say we named the environment *webdevstream*.
5.   Activate the conda environment by writing the following into your terminal: `conda activate myenv` where you replace *myenv* with your chosen name for the environment.
6.   Install *streamlit* into your conda environment by writing into your terminal: `pip install streamlit`
6.   Create a new directory on your computer, e.g. `webDevFolder`
7.   Create a new Python file within that directory, e.g. `app.py`
8.   Write your Streamlit code within that Python file on an interface where you can write Python code
9.   In the Terminal, make sure you are in the new directory you created. If not, write `cd webDevFolder`
10.   Run the app by typing `streamlit run app.py`
"""

# Importing necessary libraries
import matplotlib.pyplot as plt
import streamlit as st
import pandas as pd
import numpy as np
import time  # we'll use this later

"""## Title and Intro"""

# st.title() makes a large title at the top of the page
st.title("My Cool Dashboard!")

# st.subheader() is a smaller heading
st.subheader("An analysis of the stuff that I analyzed")

# st.write() can display plain text or variables
st.write("This app displays many interactive elements that give insight into the data I analyzed.")

"""## Text Elements"""

# st.header() creates a section header
st.header("1. Text and Formatting")

# st.markdown() supports Markdown formatting (similar to formatting you might use with LaTex. There is also a LaTex formatting feature.)
st.markdown("""
- **Bold text**
- *Italic text*
- Links: [Streamlit website](https://streamlit.io)
""")

"""## Widgets"""

st.header("2. Widgets (User Inputs)")

# Text input box (default value = "Guest")
name = st.text_input("Enter your name:", "Guest")

# Slider (range: 0 to 100, default = 25)
age = st.slider("What is your age?", 0, 100, 25)

# Dropdown menu
zodiac = st.selectbox("Your star sign:", ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",  "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"])

# Display user inputs dynamically
st.write(f"Hello **{name}**! You are {age} years old and your star sign is {zodiac}!")

"""## Charts"""

st.header("3. Charts and Plots")

# Random dataset (20 rows, 3 columns). When creating an actual dashboard, you will use real data.
chart_data = pd.DataFrame(
    np.random.randn(20, 3),
    columns=["A", "B", "C"]
)

# Line chart
st.line_chart(chart_data)

# Bar chart
st.bar_chart(chart_data)

# Area chart
st.area_chart(chart_data)


# Note that we can simply use a dataframe as the argument and it seamlessly creates the chart!

"""## Layout"""

st.header("4. Layout and Columns")

# Create two columns side by side
col1, col2 = st.columns(2)

with col1:
    st.write("Left column chart")
    st.area_chart(chart_data)

with col2:
    st.write("Right column chart")
    st.scatter_chart(chart_data)

"""## Session State

We can keep values stored within a session (and use them to calculate things)!
"""

st.header("5. Session State (Keeping Data for a Session)")

# Initialize counter if it doesn't exist yet
if "counter" not in st.session_state:
    st.session_state.counter = 0

# Button to increment counter
if st.button("Increment counter"):
    st.session_state.counter += 1

# Display current counter value
st.write("Counter value:", st.session_state.counter)

"""## Progress Bar"""

st.header("6. Progress & Status")

# st.progress() makes a progress bar (0 to 100)
progress = st.progress(0)

# Use loop to update the progress bar
for i in range(100):
    time.sleep(0.01)
    progress.progress(i + 1)

st.success("Done!")  # success message with green box


# For practical applications, you can make the progress bar align with something meaningful on the page.

"""## Media"""

st.header("7. Images and Media")

# Display an image from the web
st.image("https://placekitten.com/400/250", caption="Cute kitten 😺")

# Embed a video
st.video("https://www.w3schools.com/html/mov_bbb.mp4")

"""##  Putting Everything Together in One Section

Note that Streamlit follows top-to-bottom logic. It executes scripts top-to-bottom on every rerun, which also happens when a user interacts with a widget. Let's say you have:

`a = st.text_input("Enter value for a", "N/A")` <br>
`c = a` <br>
If the user changes the inputted value, then the values of both `a` and `c` will change.
However, if you have:

`a = "N/A"` <br>
`c = a` <br>
`a = st.text_input("Enter value for a", "N/A")`

If the user changes the inputted value, then the value of `c` will not change.

Below is an example of how you can combine what we've learned to create a more complex interactive section. Feel no need to understand all the logic and calculations--the main point is to show what streamlit is capable of.
"""

st.header("8. Putting Everything Together")

st.write("You are a competitive chess player. You are about to play in a chess tournament, but you want to first know how your chess ELO rating could change and what your prospects look like.")

user_rating = st.number_input("What is your current rating?", value=1200)
games = st.number_input(
    "How many games/opponents in your tournament?",
    min_value=1,
    max_value=10,
    value=5,
    step=1
)

new_cols = st.columns(games)

ratings = []
for i, col in enumerate(new_cols):
    with col:
        rating = st.number_input(
            f"Opponent {i+1} rating",
            min_value=0,
            max_value=3000,
            value=1200,
            step=10,
            key=f"rating_{i}"
        )
        ratings.append(rating)

# Elo update function
def elo_update(Ra, Rb, outcome, K=32):
    # outcome = 1 if win, 0 if loss
    Ea = 1 / (1 + 10 ** ((Rb - Ra) / 400))
    return Ra + K * (outcome - Ea)

opponent_ratings = ratings

st.subheader("Expected Points per Game (Elo)")

rows = []
Ra = user_rating

for i, Rb in enumerate(opponent_ratings):
    Ea = 1 / (1 + 10 ** ((Rb - Ra) / 400))  # expected points this game (0..1)
    rows.append({
        "Game": i + 1,
        "Opponent Rating": Rb,
        "Expected Points (0–1)": round(Ea, 4)
    })

exp_df = pd.DataFrame(rows)
st.dataframe(exp_df, use_container_width=True)

# Summary stats
expected_total_points = exp_df["Expected Points (0–1)"].sum()
expected_score_pct = 100 * exp_df["Expected Points (0–1)"].mean()

st.markdown(f"**Expected total points:** {expected_total_points:.2f} / {len(opponent_ratings)}")
st.markdown(f"**Expected score percentage:** {expected_score_pct:.1f}%")


if opponent_ratings:
    # All wins scenario
    rating_all_wins = [user_rating]
    Ra = user_rating
    for Rb in opponent_ratings:
        Ra = elo_update(Ra, Rb, outcome=1)
        rating_all_wins.append(Ra)

    # All losses scenario
    rating_all_losses = [user_rating]
    Ra = user_rating
    for Rb in opponent_ratings:
        Ra = elo_update(Ra, Rb, outcome=0)
        rating_all_losses.append(Ra)

    # Summary
    st.subheader("Results")
    st.write("Maximum rating after tournament:", round(rating_all_wins[-1]))
    st.write("Minimum rating after tournament:", round(rating_all_losses[-1]))

    # Approximate distribution after tournament (probabilities)
    Ra = user_rating
    prob_distribution = {}
    def dfs(i, Ra, prob):
        if i == len(opponent_ratings):
            prob_distribution[round(Ra)] = prob_distribution.get(round(Ra), 0) + prob
            return
        Rb = opponent_ratings[i]
        Ea = 1 / (1 + 10 ** ((Rb - Ra) / 400))
        # Branch win
        dfs(i+1, elo_update(Ra, Rb, 1), prob * Ea)
        # Branch loss
        dfs(i+1, elo_update(Ra, Rb, 0), prob * (1 - Ea))
    dfs(0, user_rating, 1.0)

    dist_df = pd.DataFrame(list(prob_distribution.items()), columns=["Rating", "Probability"]).sort_values("Rating")

    # Plot progression lines
    fig, ax = plt.subplots(figsize=(7,5))
    ax.plot(range(len(rating_all_wins)), rating_all_wins, label="All Wins", color="green")
    ax.plot(range(len(rating_all_losses)), rating_all_losses, label="All Losses", color="red")
    ax.set_xlabel("Games")
    ax.set_ylabel("Rating")
    ax.legend()
    st.pyplot(fig)

    # Plot probability distribution
    st.subheader("Final Rating Probability Distribution")
    st.bar_chart(dist_df.set_index("Rating"))

"""Now try to add your own section using things we've learned!

##  Other

Streamlit has tons of other functionalities! You can find the documentation here: https://docs.streamlit.io/develop/api-reference

## Deploying to Cloud

At this point, our website can only exist on our computer (unless we send the literal Python file to other people and give them instructions on how to open the website). We want to deploy it to the cloud to make it accessible to anyone with the link. The following steps detail how to do this:



1.   Push you Python code to a public GitHub repository
2.   Add a `requirements.txt` file listing all dependencies. In this case, this should look like:

          streamlit
          pandas
          numpy
          matplotlib

3.   Go to share.streamlit.io and sign in using your GitHub account
4.   Once you've created your account, click on "Create App" in the top right
5.   Click on "Deploy a Public App from GitHub"
6.   Follow the instructions. Use your GitHub repo link. Branch should be "master". Main file path should just be the name of your Python file with the code for the Streamlit app.
7.   Click deploy! You can copy the link and share with others!
"""